### ISSUE TITLE
Switching from com.sap.cloud.security.* 2.12.1 to 2.13.4 causes 401 response

### ISSUE THREAD

**Issue by stevschm** [SAP/cloud-security-xsuaa-integration#1066]
Hi team,
I just updated the POM from 2.12.1 to 2.13.4 for com.sap.cloud.security packages, but if I now start the server I get 401 errors.

In the Wrapper Class SpringSecurityContext the getToken() method throws an "Access forbidden: not authenticated" exception, because the Authentication object is null (JWT wasn't changed)

Some more info:
- We manually create an xsuaaCredentials and xsuaaServiceConfiguration bean
- We didn't change anything else, just updated the libs.
- We deploy our application to CF

Can someone help me with this issue?

Thank you and best regards,
Steve

P.S. Maybe this is related to #955

**Comment by liga-oz** [comment]
Hi @stevschm,

at which validation step does it fail? Could you provide debugging logs for that?

Thanks,
Liga

**Comment by stevschm** [comment]
Hi Liga,
here is the log, if you need more information please let me know.

```

2023-01-17 09:23:22,435 [39mDEBUG[0;39m [http-nio-8080-exec-4]-[o.s.security.web.FilterChainProxy       ] [] - Securing GET /api/jwtecho
2023-01-17 09:23:22,436 [39mDEBUG[0;39m [http-nio-8080-exec-4]-[s.s.w.c.SecurityContextPersistenceFilter] [] - Set SecurityContextHolder to empty SecurityContext
2023-01-17 09:23:22,437 [39mDEBUG[0;39m [http-nio-8080-exec-4]-[o.s.s.o.s.r.a.JwtAuthenticationProvider ] [] - Failed to authenticate since the JWT was invalid
org.springframework.security.access.AccessDeniedException: Access forbidden: not authenticated
	at com.sap.cloud.security.xsuaa.token.SpringSecurityContext.getToken(SpringSecurityContext.java:38)
	at com.sap.drs.security.UserInfo.getToken(UserInfo.java:71)
	at com.sap.drs.security.UserInfo.getIdentityZone(UserInfo.java:138)
	at com.sap.drs.security.UserInfo$$FastClassBySpringCGLIB$$828dc6e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.sap.drs.security.UserInfo$$EnhancerBySpringCGLIB$$e8b6e887.getIdentityZone(<generated>)
	at com.sap.drs.security.UserInfo$$FastClassBySpringCGLIB$$828dc6e5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.sap.drs.security.UserInfo$$EnhancerBySpringCGLIB$$da9b279f.getIdentityZone(<generated>)
	at com.sap.drs.util.audit.AuditLogger.logSecurityEventAuditMessage(AuditLogger.java:336)
	at com.sap.drs.util.audit.AuditApplicationEventListener.auditEventHappened(AuditApplicationEventListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.actuate.security.AbstractAuthenticationAuditListener.publish(AbstractAuthenticationAuditListener.java:50)
	at com.sap.drs.util.audit.ExposeDetailsAuthenticationAuditListener.onAuthenticationFailureEvent(ExposeDetailsAuthenticationAuditListener.java:48)
	at com.sap.drs.util.audit.ExposeDetailsAuthenticationAuditListener.onApplicationEvent(ExposeDetailsAuthenticationAuditListener.java:36)
	at com.sap.drs.util.audit.ExposeDetailsAuthenticationAuditListener.onApplicationEvent(ExposeDetailsAuthenticationAuditListener.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.security.authentication.DefaultAuthenticationEventPublisher.publishAuthenticationFailure(DefaultAuthenticationEventPublisher.java:116)
	at org.springframework.security.authentication.ProviderManager.prepareException(ProviderManager.java:249)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:242)
	at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:130)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
	at org.springframework.security.web.debug.DebugFilter.invokeWithWrappedRequest(DebugFilter.java:90)
	at org.springframework.security.web.debug.DebugFilter.doFilter(DebugFilter.java:78)
	at org.springframework.security.web.debug.DebugFilter.doFilter(DebugFilter.java:67)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Best regards,
Steve

**Comment by liga-oz** [comment]
Hi @stevschm,

looks like spring swallows the error message why the token was invalid. Could you verify that the XsuaaServiceConfiguration was loaded correctly and contains the attributes like `clientid`, `xsappname`, `url` etc.?

Kind Regards,
Liga

**Comment by stevschm** [comment]
@liga-oz 
This is how the XsuaaServiceConfigurationCustom object looks like:
![image](https://user-images.githubusercontent.com/10450071/214249227-aba306d5-5f96-406f-b495-765dea803b81.png)

XsuaaServiceConfiguration:
```
    @Bean
    public XsuaaServiceConfiguration customXsuaaConfig() throws IOException {
        if (Arrays.stream(env.getActiveProfiles()).anyMatch(str -> str.equalsIgnoreCase("localsecurity"))) {
            return new XsuaaServiceConfigurationCustom(mockedXsuaaCredentials());
        }
        return new XsuaaServiceConfigurationCustom(xsuaaCredentials());
    }

```
mockedXsuaaCredentials:
```
    @Bean
    @Profile("localSecurity")
    public XsuaaCredentials mockedXsuaaCredentials() throws IOException {
        XsuaaCredentials xsuaaCredentials = new XsuaaCredentials();
        xsuaaCredentials.setClientId("XXXXXXXX");
        xsuaaCredentials.setClientSecret("XXXXXXXX");
        xsuaaCredentials.setUaaDomain("XXXXXXXX");
        xsuaaCredentials.setUrl("XXXXXXXX");
        xsuaaCredentials.setVerificationKey("-----BEGIN PUBLIC KEY-----XXXXXXXX-----END PUBLIC KEY-----");
        xsuaaCredentials.setXsAppName("XXXXXXXX");
        return xsuaaCredentials;
    }
```

**Comment by liga-oz** [comment]
Hi @stevschm,

I tried out the sample app with your provided service configuration setup and couldn't reproduce the issue and when mocking different token validation failures I could also see additional logs at which place the validation failed, but from the logs and stack trace you provided it's not present at all, so I'm guessing that the `XsuaaJwtDecoder` is not being used.

In the latest release 2.13.5 I've added the debug logging output for `XsuaaAudienceValidator`  perhaps you could try to run your app with this version and see if we get any additional debug logs. 

Could you please provide your app's dependency tree as well as the `SecurityConfiguration` 

Thanks,
Liga

**Comment by clnative** [comment]
Hi @stevschm,

We experienced a similar issue when we bumped from 2.11.14 to 2.13.4. When testing locally with JWTs that can only be verified by offline validation, all our endpoints with JWT validation responded with 401 (no change in JWT compared to before, as in your case). 
The `error_description` in the response was this: "JWT verification failed: Cannot verify with online token key, jku, kid, uaadomain is null".
When searching through the repository, we found 0f16cd6fdcb8f984e6f4f924bc64e043d1535348, which restricted the offline JWT verification to specific error cases only. 
The solution that worked for us was to add some arbitrary jku and kid values to the header of our local test JWT.
Hope this helps!

**Comment by stevschm** [comment]
> Hi @stevschm,
> 
> We experienced a similar issue when we bumped from 2.11.14 to 2.13.4. When testing locally with JWTs that can only be verified by offline validation, all our endpoints with JWT validation responded with 401 (no change in JWT compared to before, as in your case).  The `error_description` in the response was this: "JWT verification failed: Cannot verify with online token key, jku, kid, uaadomain is null". When searching through the repository, we found [0f16cd6](https://github.com/SAP/cloud-security-xsuaa-integration/commit/0f16cd6fdcb8f984e6f4f924bc64e043d1535348), which restricted the offline JWT verification to specific error cases only.  The solution that worked for us was to add some arbitrary `jku` and `kid` values to the header of our local test JWT. Hope this helps!

@clnative and @liga-oz I added the jku and kid field to the header of our test JWT and now it works :)
Thanks to both of you!
