### ISSUE TITLE
"Unexpected principal type" error when trying to do a POST method locally

### ISSUE THREAD

**Issue by lcavalet** [SAP/cloud-security-xsuaa-integration#247]
Hello,

I am opening this issue as a way to understand the error I got when I try to do a POST calling a SpringBoot application with a VCAP_SERVICES that point to local database.
To be more clear 
- I am using IntelliJ with VCAP_SERVICES configured as my environment variable
- The VCAP_SERVICES I got from my application that was running on Cloud Foundry and I modified the database URI to point to the database I have in my local machine
- I have no profiles activated (no local profile activated)
- The spring.xsuaa.version is 2.5.1

This set up is working fine and the log I get from SpringBoot is shown below:
```
No active profile set, falling back to default profiles: default
INFO 17836 --- [           main] .c.s.x.XsuaaServicePropertySourceFactory : Parse {} XSUAA properties.
INFO 17836 --- [           main] .c.s.x.XsuaaServicePropertySourceFactory : Parsed 13 XSUAA properties.
```
Once the application is running locally, I try to make a POST. The POST call uses `localhost` as part of the application URL and for the header I used the OAuth2.0 Authorization, with a valid bearer token I got from Cloud Foundry. When the request is send I got the following error:

```
Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: Unexpected principal type
```

with the following stack trace

```
java.lang.IllegalStateException: Unexpected principal type
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at com.sap.cloud.security.xsuaa.token.SpringSecurityContext.getToken(SpringSecurityContext.java:33) ~[spring-xsuaa-1.6.0.jar:na]
	at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.<init>(SessionFactoryImpl.java:1180) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.hibernate.internal.SessionFactoryImpl.withOptions(SessionFactoryImpl.java:502) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.hibernate.internal.SessionFactoryImpl.buildEntityManager(SessionFactoryImpl.java:620) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:614) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:154) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:464) ~[spring-orm-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:390) ~[spring-orm-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:475) ~[spring-tx-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289) ~[spring-tx-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
```

As we can see by the stack trace the problem occurs on the class `Assert.java`, more specifically here
```
		Assert.state(principal instanceof Token, "Unexpected principal type");
```
 I don't understand why principal is not an instance of Token since it came from a valid JWT. Perhaps I am doing something wrong to test locally. Hope you can help me understand it.

**Comment by nenaraab** [comment]
Hi @lcavalet ,
 
first of all, according to your stacktrace you make use of spring-xsuaa version 1.6.0. But this might not matter...
 
You point out, that principal is not instance of `Token`... can you provide me the information, of which type it is?
 
And how the SpringSecurityContext is initialized with the token within your context?
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/SpringSecurityContext.java#L52
 
Furthermore you can find a sample on local test setup for web-based authentication / authorization checks here:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/samples/spring-security-xsuaa-usage
 
it leverages the [`java-security-test`](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/java-security-test) library.
 
Kind regards,
Nena

**Comment by nenaraab** [comment]
Hi @lcavalet,

due to 2 weeks inactivity i would like to close this.
We can re-open it on demand, let me know.

Best regards,
Nena

**Comment by lcavalet** [comment]
Hi @nenaraab,

Thanks for the reply. 
You can close this issue, and as soon as we get back to it, I let you know and ask for your help again.

Best regards,
Lilian
