### ISSUE TITLE
nullpointerexception

### ISSUE THREAD

**Issue by scorvio** [SAP/cloud-security-xsuaa-integration#277]
Caused by: java.lang.NullPointerException: null
	at com.sap.cloud.security.xsuaa.XsuaaServicesParser.getJSONObjectFromTag(XsuaaServicesParser.java:143) ~[spring-xsuaa-2.6.2.jar:na]
	at com.sap.cloud.security.xsuaa.XsuaaServicesParser.searchXsuaaBinding(XsuaaServicesParser.java:128) ~[spring-xsuaa-2.6.2.jar:na]
	at com.sap.cloud.security.xsuaa.XsuaaServicesParser.parseCredentials(XsuaaServicesParser.java:114) ~[spring-xsuaa-2.6.2.jar:na]
	at com.sap.cloud.security.xsuaa.XsuaaServicesParser.parseCredentials(XsuaaServicesParser.java:96) ~[spring-xsuaa-2.6.2.jar:na]
	at com.sap.cloud.security.xsuaa.XsuaaServicePropertySourceFactory.createPropertySource(XsuaaServicePropertySourceFactory.java:60) ~[spring-xsuaa-2.6.2.jar:na]
	at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:455) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:274) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:194) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:298) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 13 common frames omitted

**Comment by nenaraab** [comment]
Hi @scorvio 

thanks for reporting!
In which case, plan is not filled? This is an interesting assumption.

Anyhow, I've added a respective check with this PR, which will become effective with version 2.6.3.
https://github.com/SAP/cloud-security-xsuaa-integration/pull/278

Best regards,
Nena
