### ISSUE TITLE
No qualifying bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' available issue

### ISSUE THREAD

**Issue by MohdSaifz** [SAP/cloud-security-xsuaa-integration#368]
Hi,
Trying the approach as documented in a web application managed by spring-framework.
Would like to use PreAuthorize to secure endpoints. However, currently facing bean dependency with: 
XsuaaServiceConfiguration and JwtDecoder. (Error stack below.) 

``` --- maven-dependency-plugin:2.8:tree (default-cli) @ template-service ---
[INFO] com.sap.eql.awm.templates:template-service:war:1.0
[INFO] +- org.apache.olingo:olingo-odata2-api:jar:2.0.8-sap-06:compile
[INFO] +- org.apache.olingo:olingo-odata2-core:jar:2.0.8-sap-06:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.6:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.4:compile
[INFO] +- org.apache.olingo:olingo-odata2-jpa-processor-api:jar:2.0.8-sap-06:compile
[INFO] |  \- org.eclipse.persistence:javax.persistence:jar:2.0.5:compile
[INFO] +- org.apache.olingo:olingo-odata2-api-annotation:jar:2.0.8-sap-06:compile
[INFO] +- org.apache.olingo:olingo-odata2-jpa-processor-core:jar:2.0.8-sap-06:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
[INFO] +- org.glassfish.jersey:jersey-bom:pom:2.31:compile
[INFO] +- org.glassfish.jersey.media:jersey-media-multipart:jar:2.31:compile
[INFO] |  \- org.glassfish.jersey.core:jersey-common:jar:2.31:compile
[INFO] |     \- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] +- org.glassfish.jersey.core:jersey-client:jar:2.31:compile
[INFO] |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  \- org.glassfish.hk2.external:jakarta.inject:jar:2.6.1:compile
[INFO] +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.31:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.31:compile
[INFO] |  \- org.glassfish.jersey.core:jersey-server:jar:2.31:compile
[INFO] +- org.glassfish.jersey.ext:jersey-spring4:jar:2.31:compile
[INFO] |  +- org.glassfish.jersey.inject:jersey-hk2:jar:2.31:compile
[INFO] |  |  \- org.glassfish.hk2:hk2-locator:jar:2.6.1:compile
[INFO] |  |     \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.6.1:compile
[INFO] |  +- org.glassfish.hk2:hk2:jar:2.6.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-utils:jar:2.6.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.6.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-core:jar:2.6.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-runlevel:jar:2.6.1:compile
[INFO] |  |  \- org.glassfish.hk2:class-model:jar:2.6.1:compile
[INFO] |  |     +- org.ow2.asm:asm:jar:7.1:compile
[INFO] |  |     +- org.ow2.asm:asm-analysis:jar:7.1:compile
[INFO] |  |     +- org.ow2.asm:asm-commons:jar:7.1:compile
[INFO] |  |     +- org.ow2.asm:asm-tree:jar:7.1:compile
[INFO] |  |     \- org.ow2.asm:asm-util:jar:7.1:compile
[INFO] |  \- org.glassfish.hk2:spring-bridge:jar:2.6.1:compile
[INFO] +- org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.31:compile
[INFO] |  +- org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.31:compile
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.1:compile
[INFO] |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |     \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.31:compile
[INFO] |  +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.1.2.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
[INFO] |  \- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] +- javax.servlet:javax.servlet-api:jar:4.0.1:provided
[INFO] +- org.springframework:spring-context:jar:5.2.1.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.2.1.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-context-support:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-jdbc:jar:5.2.1.RELEASE:compile
[INFO] |  \- org.springframework:spring-tx:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-web:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-aspects:jar:5.2.1.RELEASE:compile
[INFO] |  +- org.aspectj:aspectjweaver:jar:1.9.4:compile
[INFO] |  \- org.springframework:spring-orm:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-aop:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-core:jar:5.2.1.RELEASE:compile
[INFO] |  \- org.springframework:spring-jcl:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-spring-service-connector:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-core:jar:1.2.0.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-cloudfoundry-connector:jar:1.2.0.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-localconfig-connector:jar:1.2.3.RELEASE:compile
[INFO] +- org.apache.tomcat:tomcat-jdbc:jar:9.0.37:compile
[INFO] |  \- org.apache.tomcat:tomcat-juli:jar:9.0.37:compile
[INFO] +- com.sap.cloud.db.jdbc:ngdbc:jar:2.4.76:compile
[INFO] +- org.json:json:jar:20200518:compile
[INFO] +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.11.1:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.1:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.5:compile
[INFO] +- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] +- org.javers:javers-core:jar:5.11.1:compile
[INFO] |  +- org.picocontainer:picocontainer:jar:2.15:runtime
[INFO] |  \- io.github.classgraph:classgraph:jar:4.8.78:compile
[INFO] +- commons-validator:commons-validator:jar:1.4.0:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.8.3:compile
[INFO] |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] +- org.reflections:reflections:jar:0.9.12:compile
[INFO] |  \- org.javassist:javassist:jar:3.26.0-GA:compile
[INFO] +- joda-time:joda-time:jar:2.10.6:compile
[INFO] +- io.swagger.core.v3:swagger-jaxrs2:jar:2.1.2:compile
[INFO] |  +- io.swagger.core.v3:swagger-models:jar:2.1.2:compile
[INFO] |  +- io.swagger.core.v3:swagger-annotations:jar:2.1.2:compile
[INFO] |  +- io.swagger.core.v3:swagger-integration:jar:2.1.2:compile
[INFO] |  |  \- io.swagger.core.v3:swagger-core:jar:2.1.2:compile
[INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.10.1:compile
[INFO] |  |     |  \- org.yaml:snakeyaml:jar:1.24:compile
[INFO] |  |     \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.1:compile
[INFO] |  \- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.10.1:compile
[INFO] |     \- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.10.1:compile
[INFO] +- io.swagger.core.v3:swagger-jaxrs2-servlet-initializer-v2:jar:2.1.2:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.0.4:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] +- org.apache.poi:poi:jar:4.1.2:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  \- com.zaxxer:SparseBitSet:jar:1.2:compile
[INFO] +- org.apache.poi:poi-ooxml:jar:4.1.2:compile
[INFO] |  +- org.apache.poi:poi-ooxml-schemas:jar:4.1.2:compile
[INFO] |  |  \- org.apache.xmlbeans:xmlbeans:jar:3.1.0:compile
[INFO] |  +- org.apache.commons:commons-compress:jar:1.19:compile
[INFO] |  \- com.github.virtuald:curvesapi:jar:1.06:compile
[INFO] +- javax.xml:jaxp-api:jar:1.4.2:compile
[INFO] +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.31:compile
[INFO] |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.3:compile
[INFO] +- org.jvnet.mimepull:mimepull:jar:1.9.13:compile
[INFO] +- org.springframework.security:spring-security-oauth2-jose:jar:5.2.1.RELEASE:compile
[INFO] |  +- com.nimbusds:nimbus-jose-jwt:jar:7.8:compile
[INFO] |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:compile (version selected from constraint [1.3.1,2.3])
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:5.2.1.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-oauth2-core:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-config:jar:5.2.1.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-oauth2-resource-server:jar:5.2.1.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.2.1.RELEASE:compile
[INFO] \- com.sap.cloud.security.xsuaa:spring-xsuaa:jar:2.7.7:compile
[INFO]    +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:compile
[INFO]    |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO]    +- com.sap.cloud.security.xsuaa:api:jar:2.7.7:compile
[INFO]    +- com.sap.cloud.security.xsuaa:token-client:jar:2.7.7:compile
[INFO]    |  +- com.sap.cloud.security:java-api:jar:2.7.7:compile
[INFO]    |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    +- com.github.ben-manes.caffeine:caffeine:jar:2.8.2:compile
[INFO]    |  +- org.checkerframework:checker-qual:jar:3.3.0:compile
[INFO]    |  \- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
[INFO]    \- commons-io:commons-io:jar:2.6:compile`


**Error stack:**
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' available
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:475)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
		at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
		at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
		at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1720)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:479)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:428)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
		at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
		at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
		at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
		at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
		at sun.rmi.transport.Transport$1.run(Transport.java:200)
		at sun.rmi.transport.Transport$1.run(Transport.java:197)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
		at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' available
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640)
		... 64 more
	Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' available
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
		at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1126)
		at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer$JwtConfigurer.getJwtDecoder(OAuth2ResourceServerConfigurer.java:318)
		at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer$JwtConfigurer.getAuthenticationManager(OAuth2ResourceServerConfigurer.java:329)
		at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer.getAuthenticationManager(OAuth2ResourceServerConfigurer.java:444)
		at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer.configure(OAuth2ResourceServerConfigurer.java:239)
		at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer.configure(OAuth2ResourceServerConfigurer.java:132)
		at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.configure(AbstractConfiguredSecurityBuilder.java:383)
		at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:329)
		at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
		at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:292)
		at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:79)
		at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:333)
		at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
		at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:104)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
		... 65 more
```

**Comment by MohdSaifz** [comment]
@nenaraab These are already there in the dependencies. You can verify it in the dependency tree above. 

Regards
Saif

**Comment by nenaraab** [comment]
yes, now - after formatting - its human readable :-)
org.springframework.security.oauth2.jwt.JwtDecoder is provided with `spring-security-oauth2-jose`, and its there... 

I have these assumptions:
- interference with jersey
- issue with outdates spring dependencies
- issue with security configuration

Best regards,
Nena

**Comment by MohdSaifz** [comment]
Oops. I did a Ctrl+F to search :) Thanks for formatting.
What is your recommendation. I followed as documented. Was able to overcome by adding component scan for : com.sap.cloud.security package. 

I am not sure if this is the right way. 
Although there are no runtime errors now. I have another wierd problem. 

It is not blocking access to the relative path that I have given in antMatchers("/services/**"). 
So I tried adding @PreAuthorize("hasRole('ROLE_VIEWER')") to endpoints, which seems to work. 
1. Spring is throwing the error, if I am not sending the auth object. However, its also throwing if there is an auth object being sent. Which I am not able to understand why.
2. Where is the handler where I can manage the SecurityContext()?

Regards
Saif

**Comment by nenaraab** [comment]
Is it a spring-boot app?
If not pls. have a look at the cloud-bulletinboard-ads app that is referenced here:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/Migration_JavaContainerSecurityProjects.md#samples

**Comment by nenaraab** [comment]
hi @MohdSaifz,

in regard to your question on how to setup the SecurityContext, this is documented here:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/spring-xsuaa#setup-security-context-for-http-requests 

Best regards,
Nena

I will close the issue. Please create a new one for new questions and issues.
