### ISSUE TITLE
[spring-xsuaa-test] - Exception on test execution after update to Spring 2.4.1

### ISSUE THREAD

**Issue by juergenbosch** [SAP/cloud-security-xsuaa-integration#456]
This is one of the tests which fails:
https://github.wdf.sap.corp/ProductCompliance/toolkit/blob/master/src/test/java/com/sap/pss/toolkit/controller/UrlCheckerControllerTest.java

I still use junit4.

I have a problem with the unittest since i have updated to Spring 2.4.1 and Cloud security 2.8.2 the following error occures:

java.lang.NoSuchMethodError: org.json.JSONObject.toMap()Ljava/util/Map;
	at com.sap.cloud.security.xsuaa.test.JwtGenerator.parseJwt(JwtGenerator.java:460)
	at com.sap.cloud.security.xsuaa.test.JwtGenerator.convertTokenToOAuthJwt(JwtGenerator.java:452)
	at com.sap.cloud.security.xsuaa.test.JwtGenerator.createFromClaims(JwtGenerator.java:407)
	at com.sap.cloud.security.xsuaa.test.JwtGenerator.getToken(JwtGenerator.java:285)
	at com.sap.cloud.security.xsuaa.test.JwtGenerator.getTokenForAuthorizationHeader(JwtGenerator.java:233)
	at com.sap.pss.toolkit.AbstactSpringTest.setUp(AbstactSpringTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by liga-oz** [comment]
Hi @juergenbosch,

could you please provide mvn dependency:tree output for your project, if possible?

Thanks,
Liga

**Comment by juergenbosch** [comment]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ toolkit ---
[INFO] com.sap.pss.toolkit:toolkit:jar:1.1.0
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.4.1:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.4.1:compile
[INFO] |  |  \- org.springframework:spring-context:jar:5.3.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.4.1:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.2:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.2:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.4.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.4.1:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.4.1:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.41:compile
[INFO] |  |  +- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.41:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.2:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.2:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.2:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.2:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.2:compile
[INFO] +- org.junit.vintage:junit-vintage-engine:jar:5.7.0:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  +- org.junit.platform:junit-platform-engine:jar:1.7.0:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.0:test
[INFO] |  \- junit:junit:jar:4.13.1:compile
[INFO] +- com.sap.cloud.security.xsuaa:xsuaa-spring-boot-starter:jar:2.8.2:compile
[INFO] |  +- com.sap.cloud.security.xsuaa:spring-xsuaa:jar:2.8.2:compile
[INFO] |  |  +- com.sap.cloud.security.xsuaa:api:jar:2.8.2:compile
[INFO] |  |  \- com.sap.cloud.security.xsuaa:token-client:jar:2.8.2:compile
[INFO] |  |     +- com.sap.cloud.security:java-api:jar:2.8.2:compile
[INFO] |  |     \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-security:jar:2.4.1:compile
[INFO] |  |  +- org.springframework.security:spring-security-config:jar:5.4.2:compile
[INFO] |  |  \- org.springframework.security:spring-security-web:jar:5.4.2:compile
[INFO] |  +- org.springframework.security:spring-security-oauth2-jose:jar:5.4.2:compile
[INFO] |  |  +- com.nimbusds:nimbus-jose-jwt:jar:9.1.3:compile
[INFO] |  |  |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  +- org.springframework.security:spring-security-core:jar:5.4.2:compile
[INFO] |  |  \- org.springframework.security:spring-security-oauth2-core:jar:5.4.2:compile
[INFO] |  \- org.springframework.security:spring-security-oauth2-resource-server:jar:5.4.2:compile
[INFO] +- com.sap.cloud.security.xsuaa:spring-xsuaa-mock:jar:2.8.2:compile
[INFO] |  +- com.squareup.okhttp3:mockwebserver:jar:3.14.9:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |     \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO] |  \- commons-io:commons-io:jar:2.6:compile
[INFO] +- org.springframework.boot:spring-boot-starter-log4j2:jar:2.4.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-jul:jar:2.13.3:compile
[INFO] |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] +- com.sap.hcp.cf.logging:cf-java-logging-support-servlet:jar:3.3.0:compile
[INFO] |  +- com.sap.hcp.cf.logging:cf-java-logging-support-core:jar:3.3.0:compile
[INFO] |  |  +- com.fasterxml.jackson.jr:jackson-jr-objects:jar:2.11.3:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO] |  +- com.auth0:java-jwt:jar:3.8.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.11.3:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.3:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.11.3:compile
[INFO] +- com.sap.hcp.cf.logging:cf-java-logging-support-log4j2:jar:3.3.0:compile
[INFO] +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.13.3:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.13.3:compile
[INFO] +- com.sap.hcp.cf.logging:cf-custom-metrics-clients-spring-boot:jar:3.3.0:compile
[INFO] |  +- com.sap.hcp.cf.logging:cf-custom-metrics-clients-core:jar:3.3.0:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  \- org.springframework.boot:spring-boot-dependencies:pom:2.0.6.RELEASE:import
[INFO] +- commons-validator:commons-validator:jar:1.7:compile
[INFO] |  +- commons-digester:commons-digester:jar:2.1:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.16:compile
[INFO] +- org.springframework.boot:spring-boot-starter-cache:jar:2.4.1:compile
[INFO] |  \- org.springframework:spring-context-support:jar:5.3.2:compile
[INFO] +- com.github.ben-manes.caffeine:caffeine:jar:2.8.8:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.8.0:compile
[INFO] |  \- com.google.errorprone:error_prone_annotations:jar:2.4.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.4.1:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.4.1:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.4.1:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.18.1:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.0:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.0:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.0:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.0:test
[INFO] |  +- org.mockito:mockito-core:jar:3.6.28:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.18:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.18:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.1:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.6.28:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.2:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.7.0:test
[INFO] \- com.sap.cloud.security.xsuaa:spring-xsuaa-test:jar:2.8.2:test
[INFO]    +- org.springframework.security:spring-security-jwt:jar:1.1.1.RELEASE:test
[INFO]    |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:test
[INFO]    |     \- org.bouncycastle:bcprov-jdk15on:jar:1.64:test
[INFO]    \- org.json:json:jar:20200518:compile

**Comment by nenaraab** [comment]
Hi @liga-oz 
you can maybe reproduce using this sample:
https://github.com/SAP-samples/teched2019-cloud-cf-product-list/blob/teched2019/samples/spring/pom.xml
Best regards,
Nena

**Comment by liga-oz** [comment]
Hi @juergenbosch,

the issue occurs because you have  multiple occurrences of org.json.JSONObject in the class path:
1. [INFO] | | - com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
2. [INFO] - org.json:json:jar:20200518:compile

as they are conflicting maven resolves the first occurrence `android-json`, which as we can can see doesn't have the method `toMap()`, hence the `java.lang.NoSuchMethodError`. `spring-xsuaa-test` uses `org.json` dependency.
To solve the issue you can exclude it from spring-boot-starter-test dependency like so:
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.vaadin.external.google</groupId>
            <artifactId>android-json</artifactId>
        </exclusion>
    </exclusions>
    <scope>test</scope>
</dependency>
```
You can find detailed information about classpath issues [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/docs/Troubleshooting_JsonClasspathIssues.md#conflicting-library).

Kind Regards,
Liga

**Comment by juergenbosch** [comment]
Thank you it worked
