### ISSUE TITLE
Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]

### ISSUE THREAD

**Issue by prateekprshr-nith** [SAP/cloud-security-xsuaa-integration#493]
Hi Colleagues

We make use of below dependencies in our Java CAP Classic project, running on cloud foundry:

```
		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>api</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.sap.cloud.security</groupId>
			<artifactId>java-security</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>token-client</artifactId>
			<version>2.7.3</version>
		</dependency>
```

We are on spring `5.3.2` and recently upgraded spring-security to `5.4.5`. After this upgrade, we are experiencing below exceptions during application startup:

```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChainProxySecurityConfigurer' parameter 1; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'offlineTokenServices' defined in com.sap.excisetax.security.WebSecurityConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud]: Factory method 'offlineTokenServices' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
```

Below is the stacktrace:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChainProxySecurityConfigurer' parameter 1; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'offlineTokenServices' defined in com.sap.excisetax.security.WebSecurityConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud]: Factory method 'offlineTokenServices' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:722)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
Caused by: org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'offlineTokenServices' defined in com.sap.excisetax.security.WebSecurityConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud]: Factory method 'offlineTokenServices' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at org.springframework.context.expression.StandardBeanExpressionResolver.evaluate(StandardBeanExpressionResolver.java:169)
	at org.springframework.beans.factory.support.AbstractBeanFactory.evaluateBeanDefinitionString(AbstractBeanFactory.java:1626)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:714)
	... 24 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'offlineTokenServices' defined in com.sap.excisetax.security.WebSecurityConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud]: Factory method 'offlineTokenServices' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:671)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659)
	at org.springframework.security.config.annotation.web.configuration.AutowiredWebSecurityConfigurersIgnoreParents.getWebSecurityConfigurers(AutowiredWebSecurityConfigurersIgnoreParents.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:129)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:139)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:55)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:387)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:272)
	at org.springframework.context.expression.StandardBeanExpressionResolver.evaluate(StandardBeanExpressionResolver.java:166)
	... 28 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'offlineTokenServices' defined in com.sap.excisetax.security.WebSecurityConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud]: Factory method 'offlineTokenServices' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1585)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1549)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1468)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 52 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud]: Factory method 'offlineTokenServices' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 68 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud.<init>(SAPOfflineTokenServicesCloud.java:127)
	at com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud.<init>(SAPOfflineTokenServicesCloud.java:111)
	at com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud.<init>(SAPOfflineTokenServicesCloud.java:98)
	at com.sap.excisetax.security.WebSecurityConfig.offlineTokenServices(WebSecurityConfig.java:181)
	at com.sap.excisetax.security.WebSecurityConfig$$EnhancerBySpringCGLIB$$3a77dcd9.CGLIB$offlineTokenServices$1(<generated>)
	at com.sap.excisetax.security.WebSecurityConfig$$EnhancerBySpringCGLIB$$3a77dcd9$$FastClassBySpringCGLIB$$d30116ac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.sap.excisetax.security.WebSecurityConfig$$EnhancerBySpringCGLIB$$3a77dcd9.offlineTokenServices(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 69 more
Caused by: java.lang.ClassNotFoundException: org.springframework.web.client.HttpClientErrorException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:444)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:480)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	... 83 more
```

Below is the dependency tree for our application and it does include the `jar` (`spring-web-5.3.2.jar`) containing class `org.springframework.web.client.HttpClientErrorException`:

```
+- org.springframework.security.oauth:spring-security-oauth2:jar:2.5.0.RELEASE:compile
|  +- org.springframework:spring-beans:jar:5.3.2:compile
|  +- org.springframework:spring-core:jar:5.3.2:compile
|  |  \- org.springframework:spring-jcl:jar:5.3.2:compile
|  +- org.springframework:spring-context:jar:5.3.2:compile
|  +- org.springframework:spring-webmvc:jar:5.3.2:compile
|  |  \- org.springframework:spring-web:jar:5.3.2:compile <<--------------------See Here
|  +- org.springframework.security:spring-security-config:jar:5.4.5:compile
|  +- org.springframework.security:spring-security-web:jar:5.4.5:compile
|  \- commons-codec:commons-codec:jar:1.14:compile
```

We request you to examine this issue and let us know about a possible fix.

Regards

**Comment by liga-oz** [comment]
Hi @prateekprshr-nith,

Considering the information you have given:
1. You should use the latest version of `cloud-security-xsuaa-integration` libraries which is 2.8.8
2. From the dependency tree snippet, doesn't even seem to be a transitive dependency of `java-security` (at least I can't see it in the provided snippet)
3. `org.springframework.security.oauth:spring-security-oauth2` is [deprecated](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide) and only optionally needed in `java-security` for the spring adapter used by [migration projects ](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SpringSecurityProjects.md#deprecation-notice). [Migration guide](https://github.com/SAP-samples/teched2020-DEV263/tree/main/exercises/ex4_java/migrationguides#migration-guide-for-xsa-web-applications-using-spring-security-with-less-migration-effort) for the same.

BR,
Liga

**Comment by prateekprshr-nith** [comment]
Hi @liga-oz 

We get the same errors with `2.8.8` as well. Can you please analyze further and tell us which component from XSUAA depends on / uses `org.springframework.web.client.HttpClientErrorException` and thus which specific version of dependency `org.springframework.security:spring-security-web`?

From the stack trace it is clear that this error comes from XSUAA code itself during instantiation of `com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud`:

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud.<init>(SAPOfflineTokenServicesCloud.java:127)
	at com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud.<init>(SAPOfflineTokenServicesCloud.java:111)
	at com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud.<init>(SAPOfflineTokenServicesCloud.java:98)
	at com.sap.excisetax.security.WebSecurityConfig.offlineTokenServices(WebSecurityConfig.java:181)
	at com.sap.excisetax.security.WebSecurityConfig$$EnhancerBySpringCGLIB$$3a77dcd9.CGLIB$offlineTokenServices$1(<generated>)
	at com.sap.excisetax.security.WebSecurityConfig$$EnhancerBySpringCGLIB$$3a77dcd9$$FastClassBySpringCGLIB$$d30116ac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.sap.excisetax.security.WebSecurityConfig$$EnhancerBySpringCGLIB$$3a77dcd9.offlineTokenServices(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 69 more
```

Also 

> From the dependency tree snippet, doesn't even seem to be a transitive dependency of java-security (at least I can't see it in the provided snippet)

Dependency `org.springframework.security:spring-security-web` is getting resolved from some other dependency, but this doesn't mean that it's not a dependency of some XSUAA Component (may not be a dependency of java-security, but it may be of some other XSUAA component).


Regards

**Comment by liga-oz** [comment]
Hi @prateekprshr-nith,

this is XSUAA client library not XSUAA server, therefore you don't impact XSUAA components. I can verify that both versions of `spring-web` 5.4.2 and 5.3.2 works with `token-client` and `java-security` as they both include the `HttpClientErrorException`.

To answer your question where this exception is used in Xsuaa client library:
`org.springframework.web.client.HttpClientErrorException` is coming from `com.sap.cloud.security.xsuaa.client.SpringOAuth2TokenKeyService` or `com.sap.cloud.security.xsuaa.client.SpringOidcConfigurationService` which is used in `com.sap.cloud.security.adapter.spring.SAPOfflineTokenServicesCloud`


>Dependency org.springframework.security:spring-security-web is getting resolved from some other dependency, but this doesn't mean that it's not a dependency of some XSUAA Component (may not be a dependency of java-security, but it may be of some other XSUAA component).

Correct, but what it does mean is that the version definition is not coming from `cloud-security-xsuaa-integration` library. In fact, `spring-web` and `spring-security-oauth2` dependencies are defined with scope provided in `token-client` and `java-security` pom files. 

What I can suggest you is to check for Spring projects' version conflicts that could cause `java.lang.NoClassDefFoundError` errors. Most likely it's these 2 different versions that are resolved alongside:
```xml
|  +- org.springframework:spring-webmvc:jar:5.3.2:compile
|  |  \- org.springframework:spring-web:jar:5.3.2:compile <<--------------------See Here
|  +- org.springframework.security:spring-security-config:jar:5.4.5:compile
|  +- org.springframework.security:spring-security-web:jar:5.4.5:compile
```

BR,
Liga

**Comment by prateekprshr-nith** [comment]
Hi @liga-oz 

Sorry for the confusing terminology. By XSUAA, I was referring to the client library itself. Anyways, I checked dependency tree again and there are not version conflicts for any spring dependencies. Also `org.springframework.web.client.HttpClientErrorException` is present in the classpath. I verified this by following code snippet:

```java
new HttpClientErrorException(...);
```
There are no errors when above snippet executes and a new instance of `HttpClientErrorException` is created. However when I try to instantiate `SpringOidcConfigurationService` or `SpringOAuth2TokenKeyService`, I again get the `java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException`.

Also upon debugging, I can see that for direct instantiation of `HttpClientErrorException` via `new HttpClientErrorException(...)`, the classloader is:
```java
ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader [id=46404,parents=System@10833]
```
and I can call `loadClass("org.springframework.web.client.HttpClientErrorException")` on this classloader without any errors.

However when instantiating `SpringOidcConfigurationService` or `SpringOAuth2TokenKeyService` via below snippets:
```java
new SpringOidcConfigurationService(new RestTemplate());
```
```java
new SpringOAuth2TokenKeyService(new RestTemplate())
```
the classloader is:
```java
java.net.URLClassLoader [id=46404,parents=System@10833]
```
(parent of previous classloader) and calling `loadClass("org.springframework.web.client.HttpClientErrorException")` on this classloader leads to `java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException`.

I request you to analyze that why a different, wrong classloader is being used while `SAPOfflineTokenServicesCloud` tries to instantiate `SpringOidcConfigurationService` and `SpringOAuth2TokenKeyService`.

Regards

**Comment by liga-oz** [comment]
Hi @prateekprshr-nith,

Have you added spring-web dependency like below:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/token-client#configuration-for-javaspring-applications

**Comment by prateekprshr-nith** [comment]
Hi @liga-oz 

Yes, this dependency is present.

Regards

**Comment by nenaraab** [comment]
Hi @prateekprshr-nith,

please provide us the full (effective) mvn dependency tree of your application as described here:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/java-security#troubleshoot (debug logs might not be required)
Otherwise we can not support you. 

As @liga-oz already mentioned, spring-web is neither provided by token-client lib nor by java-security client lib.

Closing this one, as it is a duplicate of internal Github Ticket:
https://github.wdf.sap.corp/xs2-java/xs-java-buildpack/issues/853

Kind regards
BTP Security team
