### ISSUE TITLE
NoClassDefFoundError: CredentialType 

### ISSUE THREAD

**Issue by rahuldeepattri** [SAP/cloud-security-xsuaa-integration#602]
Hi Maintainers,

We are an SAP team leveraging autoconfiguration and we upgraded from version 2.8.2 to 2.10.2
```xml
                 <dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>xsuaa-spring-boot-starter</artifactId>
			<version>2.10.2</version>	
		</dependency>
```

After the upgrade we started getting this error.
```
 INFO	-	java.lang.NoClassDefFoundError: com/sap/cloud/security/config/CredentialType
 INFO	-		at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app/:na]
 INFO	-		at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-	2021-07-25 15:41:48.923 ERROR 8 --- [ main] o.s.boot.SpringApplication : Application run failed
 INFO	-		at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:135) ~[app/:na]
 INFO	-		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.2.jar:2.5.2]
 INFO	-		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
 INFO	-		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
 INFO	-		at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app/:na]
 INFO	-		at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app/:na]
 INFO	-		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.2.jar:2.5.2]
 INFO	-		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
 INFO	-		at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
 INFO	-		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.2.jar:2.5.2]
 INFO	-		at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at java.lang.ClassLoader.loadClass(ClassLoader.java:480) ~[na:1.8.0_291]
 INFO	-		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.2.jar:2.5.2]
 INFO	-		at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-	Caused by: java.lang.ClassNotFoundException: com.sap.cloud.security.config.CredentialType
 INFO	-		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		... 26 common frames omitted
 INFO	-		at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app/:na]
 INFO	-		at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.2.jar:2.5.2]
 INFO	-		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.2.jar:2.5.2]
 INFO	-		at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at com.admin.Application.main(Application.java:16) [classes/:na]
 INFO	-		at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at java.lang.ClassLoader.loadClass(ClassLoader.java:413) ~[na:1.8.0_291]
 INFO	-		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.7.jar:5.3.7]
 INFO	-		at com.sap.cloud.security.xsuaa.autoconfiguration.XsuaaAutoConfiguration$OnNotX509CredentialTypeCondition.matches(XsuaaAutoConfiguration.java:113) ~[spring-xsuaa-2.10.2.jar:na]
 INFO	-		at java.net.URLClassLoader.findClass(URLClassLoader.java:444) ~[na:1.8.0_291]
```

Looks like https://github.com/SAP/cloud-security-xsuaa-integration/issues/558

We request your support on this.

Best Regards
Rahul

**Comment by liga-oz** [comment]
Hi @rahuldeepattri,

please read carefully [Reporting an Issue](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/CONTRIBUTING.md#report-an-issue) section and provide us with the information necessary to analyze the issue.

Kind Regards,
Liga

**Comment by rahuldeepattri** [comment]
Hi @liga-oz ,

Thanks for your quick response! 
Upon checking the POM, I realized that wrong version of api was resolved.
`(com.sap.cloud.security.xsuaa:api:jar:2.9.0:compile - omitted for conflict with 2.10.2)`

I have added https://github.com/SAP/cloud-security-xsuaa-integration/pull/603 which will help to avoid these kind of issues in future.

Best Regards
Rahul

**Comment by liga-oz** [comment]
Hi @rahuldeepattri,

thanks for your contribution. 👍🏻 

Kind Regards,
Liga
