### ISSUE TITLE
XsTokenFlows autowired bean does not create token, give 401. Explicit instanitation of XsTokenFlows works?

### ISSUE THREAD

**Issue by kiranbadala** [SAP/cloud-security-xsuaa-integration#681]
**Question Summary**
Hi Team,
We are using the "xsuaa-spring-boot-starter" library in our app and trying to create token using XsTokenFlows after autowiring as suggested in the git page. But failed with error 401. Then I tried to instantiate XsTokenFlows similar to the example given for java apps.
Please let us know if we have to make any extra configurations for autowired bean to work.
And also confirm if XsTokenFlows bean explicit instantiation in spring boot apps can be done?

If applicable, please mention:
- client library : xsuaa-spring-boot-starter-2.10.5
- Environment: Cloud Foundry
- Additional information : 

My Xsuaa configuration from MTA:
     xsappname: market-data-${org}-${space}
      oauth2-configuration:
        credential-types:
          - x509
          - binding-secret
    service-plan: broker

My Security Config java file contents:

public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

	@Autowired
	private XsuaaServiceConfiguration xsuaaServiceConfiguration;

	@Autowired
	XsuaaTokenFlows xsuaaTokenFlows;

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		// @formatter:off
		http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and().authorizeRequests()
				.antMatchers(HEALTH_ENDPOINT).permitAll()
				.anyRequest().authenticated()
	            .and()
	                .oauth2ResourceServer()
	                .bearerTokenResolver(new IasXsuaaExchangeBroker(xsuaaTokenFlows))
	                .jwt()
	                .jwtAuthenticationConverter(getJwtAuthoritiesConverter());
		// @formatter:on
	}
	Converter<Jwt, AbstractAuthenticationToken> getJwtAuthoritiesConverter() {
		TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration);
		converter.setLocalScopeAsAuthorities(true);
		return converter;
	}

	@Bean
	JwtDecoder jwtDecoder() {
		return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).build();
	}

**Comment by kiranbadala** [comment]
2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR com.sap.cloud.security.xsuaa.tokenflows.TokenFlowException: Error requesting technical user token with grant_type 'client_credentials': Error retrieving JWT token. Received status code 401 UNAUTHORIZED. Call to XSUAA was not successful:
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.tokenflows.ClientCredentialsTokenFlow.requestTechnicalUserToken(ClientCredentialsTokenFlow.java:188)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.tokenflows.ClientCredentialsTokenFlow.execute(ClientCredentialsTokenFlow.java:141)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.bs.fmd.metering.services.MeteringService.isWhitelistedGA(MeteringService.java:163)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.bs.fmd.metering.controller.MeteringController.marketdataInternalConsumerGlobalAcctIdGet(MeteringController.java:44)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at java.lang.reflect.Method.invoke(Method.java:498)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.hcp.cf.logging.servlet.filter.RequestLoggingFilter.doFilterRequest(RequestLoggingFilter.java:122)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.hcp.cf.logging.servlet.filter.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:74)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:129)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at java.lang.Thread.run(Thread.java:836)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR Caused by: com.sap.cloud.security.xsuaa.client.OAuth2ServiceException: Error retrieving JWT token. Received status code 401 UNAUTHORIZED. Call to XSUAA was not successful:
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.client.XsuaaOAuth2TokenService.requestAccessToken(XsuaaOAuth2TokenService.java:88)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.getAndCacheToken(AbstractOAuth2TokenService.java:305)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.getOrRequestAccessToken(AbstractOAuth2TokenService.java:263)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.getOAuth2TokenResponse(AbstractOAuth2TokenService.java:252)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.retrieveAccessTokenViaClientCredentialsGrant(AbstractOAuth2TokenService.java:112)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     at com.sap.cloud.security.xsuaa.tokenflows.ClientCredentialsTokenFlow.requestTechnicalUserToken(ClientCredentialsTokenFlow.java:183)
   2021-10-01T17:23:22.45+0530 [APP/PROC/WEB/0] ERR     ... 103 more
   2021-10-01T17:23:22.62+0530 [RTR/17] OUT mrm-dev-mrm-cpc-market-data

**Comment by liga-oz** [comment]
@kiranbadala can you check if calling manually the xsuaa endpoint with the same attributes as from the failing call succeeds or not?
