### ISSUE TITLE
Migration issue for complying with x509. Application start up failure.

### ISSUE THREAD

**Issue by divyathaore** [SAP/cloud-security-xsuaa-integration#998]
Hello Team,

I am using the below documentation for migration from java-container-security to spring security for complying with x509 SEC 374. We want to use it with XSUAA.
But I am facing the below error while configuration. I have checked the xsappname configuration and fetching it using :
https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#setup-spring-security-oauth-20-resource-server

https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/samples/spring-security-hybrid-usage

Error is : 

Field authConverter in com.sap.acrs.config.WebSecurityConfig required a bean of type 'org.springframework.core.convert.converter.Converter' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)
      
- Library used<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sap.cloud.security</groupId>
            <artifactId>resourceserver-security-spring-boot-starter</artifactId>
            <version>2.13.2</version>
        </dependency>
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
</dependency>
- Environment: Cloud Foundry

Any kind of help would be appreciated.

**Comment by liga-oz** [comment]
Hi @divyathaore,

please verify that upon application start VCAP_SERVICES properties have been loaded. You can see that in logging output
e.g.
```log
DEBUG 8897 --- [main] .c.IdentityServicesPropertySourceFactory : .c.IdentityServicesPropertySourceFactory : Parsed 13 properties from identity services. [sap.security.services.xsuaa.key,...
```

you might need to enable logging level to debug. https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#increase-log-level-to-debug 

This issue is a [common pitfall](https://github.com/SAP/cloud-security-xsuaa-integration/blob/4565f49d67e420857b0b66ff494ad68de1aec93e/spring-security/README.md#local-setup-fails-with-application-failed-to-start).

**Comment by divyathaore** [comment]
Hello @liga-oz ,

Was able to start the application, but after deploying on CF facing issues.
Logs for reference : 
2022-10-06T11:17:11.850+0000 [APP/PROC/WEB/0] OUT {"msg":"There is no 'x-forwarded-client-cert' header provided","level":"INFO","written_ts":"1665055031850000000","logger":"com.sap.cloud.security.servlet.AbstractTokenAuthenticator","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:11.850Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:11.852+0000 [APP/PROC/WEB/0] OUT {"msg":"Sets certificate to SecurityContext (thread-locally). null","level":"INFO","written_ts":"1665055031852000000","logger":"com.sap.cloud.security.token.SecurityContext","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:11.852Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:11.863+0000 [APP/PROC/WEB/0] OUT {"msg":"configured JwtAudienceValidator with clientId sb-acrs!t16458.","level":"INFO","written_ts":"1665055031863000000","logger":"com.sap.cloud.security.token.validation.validators.JwtAudienceValidator","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:11.863Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:11.863+0000 [APP/PROC/WEB/0] OUT {"msg":"configured JwtAudienceValidator with clientId acrs!t16458.","level":"INFO","written_ts":"1665055031863000000","logger":"com.sap.cloud.security.token.validation.validators.JwtAudienceValidator","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:11.863Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:11.864+0000 [APP/PROC/WEB/0] OUT {"msg":"configured JwtAudienceValidator with clientId sb-acrs!t16458.","level":"INFO","written_ts":"1665055031864000000","logger":"com.sap.cloud.security.token.validation.validators.JwtAudienceValidator","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:11.864Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:11.864+0000 [APP/PROC/WEB/0] OUT {"msg":"configured JwtAudienceValidator with clientId acrs!t16458.","level":"INFO","written_ts":"1665055031864000000","logger":"com.sap.cloud.security.token.validation.validators.JwtAudienceValidator","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:11.864Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:12.020+0000 [APP/PROC/WEB/0] OUT {"msg":"The audiences that are derived from the token: [sb-acrs!t16458, acrs!t16458, uaa, openid].","level":"INFO","written_ts":"1665055032020000000","logger":"com.sap.cloud.security.token.validation.validators.JwtAudienceValidator","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:12.020Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:12.021+0000 [APP/PROC/WEB/0] OUT {"msg":"Sets token of service XSUAA to SecurityContext (thread-locally).","level":"INFO","written_ts":"1665055032021000000","logger":"com.sap.cloud.security.token.SecurityContext","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:12.021Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:12.475+0000 [APP/PROC/WEB/0] OUT {"msg":"Setting the server's publish address to be /","level":"INFO","written_ts":"1665055032475000000","logger":"org.apache.cxf.endpoint.ServerImpl","DCComponent":"","CSNComponent":"","written_at":"2022-10-06T11:17:12.475Z","thread":"http-nio-0.0.0.0-8080-exec-2","type":"log","Application":"acrscore-java"}
2022-10-06T11:17:12.582+0000 [APP/PROC/WEB/0] OUT {"msg":"\n\n************************************************************\n\nRequest received for GET '/odata/$metadata?sap-language=EN':\n\norg.apache.catalina.connector.RequestFacade@4b22ed89\n\nservletPath:/odata\npathInfo:/$metadata\nheaders: \nhost: slhacrdev-acrsspace-acrscore-java.cfapps.sap.hana.ondemand.com\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36\naccept: application/xml\naccept-encoding: gzip, deflate, br\naccept-language: en\nauthorization: Bearer 

Do you have any idea , if we are missing anything to configure or why these logs are coming ?

Regards,
Divya

**Comment by liga-oz** [comment]
Hi @divyathaore,

I dont see any errors in the logs, what is the issue exactly?Info logs? 

Kind Regards,
Liga

**Comment by divyathaore** [comment]
Hello @liga-oz ,

Actually, when I passing correct token too for the API, there is no error but still I am getting 403 Forbidden, Thats why sharing the logs for reference if there is anything wrong which you could see ?


2022-10-12T05:44:27.979+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:27,979 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m c.s.c.s.x.c.DefaultOAuth2TokenKeyService [DCComponent=, CSNComponent=, Application=acrs-java]:: Successfully retrieved token keys from https://slhacrconsumer1.authentication.sap.hana.ondemand.com/token_keys for zone 'null'
2022-10-12T05:44:27.994+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:27,994 [http-nio-0.0.0.0-8080-exec-10] [34mINFO [0;39m c.s.c.s.t.v.v.JwtAudienceValidator [DCComponent=, CSNComponent=, Application=acrs-java]:: The audiences that are derived from the token: [sb-acrs!t16458, acrs!t16458, uaa, openid].
2022-10-12T05:44:27.994+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:27,994 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m c.s.c.s.s.t.a.HybridJwtDecoder [DCComponent=, CSNComponent=, Application=acrs-java]:: Token issued by XSUAA service was successfully validated.
2022-10-12T05:44:27.999+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:27,999 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m o.s.s.o.s.r.a.JwtAuthenticationProvider [DCComponent=, CSNComponent=, Application=acrs-java]:: Authenticated token
2022-10-12T05:44:28.000+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:28,000 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m o.s.s.o.s.r.w.BearerTokenAuthenticationFilter [DCComponent=, CSNComponent=, Application=acrs-java]:: Set SecurityContextHolder to JwtAuthenticationToken [Principal=org.springframework.security.oauth2.jwt.Jwt@da15f686, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=165.1.238.5, SessionId=null], Granted Authorities=[SCOPE_acrs!t16458.acrs.business.user.ui, SCOPE_acrs!t16458.acrs.ngopack.business.user, SCOPE_openid, SCOPE_acrs!t16458.acrs.business.user, SCOPE_acrs!t16458.acrs.erppack.business.user, SCOPE_uaa.user]]
2022-10-12T05:44:28.016+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:28,016 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m o.s.s.w.a.i.FilterSecurityInterceptor [DCComponent=, CSNComponent=, Application=acrs-java]:: Authorized filter invocation [GET /dev/hello] with attributes [permitAll]
2022-10-12T05:44:28.016+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:28,016 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m o.s.security.web.FilterChainProxy [DCComponent=, CSNComponent=, Application=acrs-java]:: Secured GET /dev/hello
2022-10-12T05:44:28.021+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:28,021 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m o.s.s.w.c.SecurityContextPersistenceFilter [correlation_id=9ff6b5d4-3bbe-4755-97a4-773606ab7648, CSNComponent=, Application=acrs-java, DCComponent=]:: Cleared SecurityContextHolder to complete request
2022-10-12T05:44:28.026+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:28,026 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m c.s.x.s.t.valve.RequestTracingValve [correlation_id=9ff6b5d4-3bbe-4755-97a4-773606ab7648, CSNComponent=, Application=acrs-java, DCComponent=]:: Next valve(s) in the chain invoked.
2022-10-12T05:44:28.026+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:28,026 [http-nio-0.0.0.0-8080-exec-10] [39mDEBUG[0;39m c.s.x.s.t.valve.RequestTracingValve [correlation_id=9ff6b5d4-3bbe-4755-97a4-773606ab7648, CSNComponent=, Application=acrs-java, DCComponent=]:: Exiting the request tracing valve.
2022-10-12T05:44:28.027+0000 [RTR/13] OUT slhacrdev-acrsspace-acrs-java.cfapps.sap.hana.ondemand.com - [2022-10-12T05:44:27.411820649Z] "GET /dev/hello HTTP/1.1" 403 0 0 "-" "PostmanRuntime/7.29.2" "10.0.200.5:53620" "10.36.134.14:61146" x_forwarded_for:"165.1.238.5, 10.0.200.5" x_forwarded_proto:"https" vcap_request_id:"b1a65ef8-007f-4dc9-7f85-d3a25dc10710" response_time:0.615293 gorouter_time:0.000059 app_id:"7fb2a0c6-bea2-4b4e-9b9d-88612081890b" app_index:"0" instance_id:"c6774040-6f31-4400-437f-2295" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"76f07a6f-db2d-4771-90c3-c21a4d5e307f-6346543B-3AAFC6" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" traceparent:"-" x_b3_traceid:"740eba5e9913a1b1523c6b047bcb3203" x_b3_spanid:"523c6b047bcb3203" x_b3_parentspanid:"-" b3:"740eba5e9913a1b1523c6b047bcb3203-523c6b047bcb3203"
2022-10-12T05:44:29.642+0000 [APP/PROC/WEB/0] OUT 05:44:29,642 |-INFO in ReconfigureOnChangeTask(born:1665552929641) - Empty watch file list. Disabling
2022-10-12T05:44:34.678+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:34,678 [quartzScheduler_QuartzSchedulerThread] [39mDEBUG[0;39m o.quartz.core.QuartzSchedulerThread []:: batch acquisition of 0 triggers
2022-10-12T05:44:34.994+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:34,993 [HikariPool-1 housekeeper] [39mDEBUG[0;39m com.zaxxer.hikari.pool.HikariPool []:: HikariPool-1 - Pool stats (total=10, active=1, idle=9, waiting=0)
2022-10-12T05:44:34.994+0000 [APP/PROC/WEB/0] OUT 2022-10-12 05:44:34,994 [HikariPool-1 housekeeper] [39mDEBUG[0;39m com.zaxxer.hikari.pool.HikariPool []:: HikariPool-1 - Fill pool skipped, pool is at sufficient level.

Let me know if we could connect over a quick call?

Regards,
Divya

**Comment by divyathaore** [comment]
@liga-oz  : 
One more issue which I am facing is : 
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfig': Unsatisfied dependency expressed through field 'authConverter'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.core.convert.converter.Converter<org.springframework.security.oauth2.jwt.Jwt, org.springframework.security.authentication.AbstractAuthenticationToken>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

I have to explicitly add this  
@Autowired**(required=false)**
 Converter<Jwt, AbstractAuthenticationToken> authConverter;
to get the application started. If I don't add required=false then application startUp itself fails. And when after adding I try to hit the API, then it says 403 Forbidden.

**Comment by liga-oz** [comment]
Hi @divyathaore ,

please do not mix multiple issues in one ticket. But as I've understood, you didn't check whether the service configuration was loaded properly, but instead introduced a hack `@Autowired (required=false)` to get the application running.

>I have to explicitly add this
@Autowired (required=false)
Converter<Jwt, AbstractAuthenticationToken> authConverter;

this is wrong if you're using xsuaa, it just leads to issues at later stage in case `xsappname` was not loaded from VCAP_SERVICES. 

https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#local-setup-fails-with-application-failed-to-start 

https://github.com/SAP/cloud-security-xsuaa-integration/issues/998#issuecomment-1266647225

**Comment by divyathaore** [comment]
@liga-oz  : 
Issue is : I have two applications. In one application without introducing required=false, its working perfectly fine.
Whereas when trying to achieve the same in other application its giving autowiring issue.
Apart from autowiring is there any other way to achieve the same ?  We are not using any explicit converter, just using the default provided as mentioned here : https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#setup-spring-security-oauth-20-resource-server

**Comment by liga-oz** [comment]
Hi @divyathaore,

for xsuaa [this](https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#custom-authorization-converter) converter is mandatory without that authorization won't work and you will get 403!

Where's the problem getting VCAP_SERVICES properly loaded for the second service?

Kind Regards,
Liga

**Comment by divyathaore** [comment]
Hey,

Thats a custom converter right ? If we add only the converterObject. Won't it work ? it's the same stated in **.jwtAuthenticationConverter(authConverter); // (1) you may want to provide your own converter**  

No problem in loading the properties, they are getting loaded and autowired using the environment file as well. Would appreciate if we can connect on the internal channel? I have dropped you a message on slack.

Regards,
Divya

**Comment by liga-oz** [comment]
Hi @divyathaore,

> Thats a custom converter right ? If we add only the converterObject. Won't it work ? it's the same stated in .jwtAuthenticationConverter(authConverter); // (1) you may want to provide your own converter 

that will work as well. for xsuaa only.

If the service configuration is loaded properly in the app context and `xsappname` is present, then there shouldn't be `NoSuchBeanDefinitionException`, please debug your application and double check that the service configuration has been loaded, moreover, that the `xsappname` is there, that is the single and only property that is required to autowire `Converter` bean.

**Comment by divyathaore** [comment]
Hi @liga-oz ,

Autowiring is not working and throwing NoSuchBeanDefinationException.
However, If I create the customConverter and use it the following way, it starts up the application.
`      .and()
                .oauth2ResourceServer().jwt(customizer -> customizer.jwtAuthenticationConverter((new CustomHybridTokenAuthenticationConverter())));`

`    class CustomHybridTokenAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {

        public AbstractAuthenticationToken convert(Jwt jwt) {

            if (jwt.hasClaim(TokenClaims.XSUAA.SCOPES)) {
                logger.info("jwt :"+ jwt.getTokenValue());
                logger.info("jwt scopes:"+ jwt.getClaimAsString(TokenClaims.XSUAA.SCOPES));
               // authConverter.convert(jwt);
            }
            return new AuthenticationToken(jwt, deriveAuthoritiesFromScope(jwt));
        }`

Note : This I added after commenting the auto wiring statement.

This should not give any issue ? Right ?

Also, xsappname is getting loaded.

Regards,
Divya

**Comment by liga-oz** [comment]
Hi @divyathaore,

depending on what you do in `deriveAuthoritiesFromScope(jwt)` method, if that's the same as the one from readme then i would expect that the authorization would fail.

Kind Regards,
Liga

**Comment by divyathaore** [comment]
Hi @liga-oz ,

I am doing it using the below code :
` class CustomHybridTokenAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {

        public AbstractAuthenticationToken convert(Jwt jwt) {
            if (jwt.hasClaim(TokenClaims.XSUAA.SCOPES)) {
                logger.info("jwt :"+ jwt.getTokenValue());
                logger.info("jwt scopes:"+ jwt.getClaimAsString(TokenClaims.XSUAA.SCOPES));
               // authConverter.convert(jwt);
            }
            return new AuthenticationToken(jwt, deriveAuthoritiesFromScope(jwt));
        }

        private Collection<GrantedAuthority> deriveAuthoritiesFromScope(Jwt jwt) {
            Collection<GrantedAuthority> scopeAuthorities = new ArrayList<>();
            if (jwt.hasClaim(TokenClaims.XSUAA.SCOPES)) {
                List<String> scopes = jwt.getClaimAsStringList(TokenClaims.XSUAA.SCOPES);
                for (String scope : scopes) {
                    logger.info("scope added:"+ scope);
                    scopeAuthorities.add(new SimpleGrantedAuthority(scope));
                }
                logger.info("scopes :"+ scopeAuthorities.toString());

            }
            return scopeAuthorities;
        }
    }`

This did not fail till now. 

But what are your views for this ?
Any issue you see ?

Regards,
Divya

**Comment by divyathaore** [comment]
Hi,

@liga-oz  : Also what is the recommended version of library for  
<groupId>com.sap.cloud.sdk.cloudplatform</groupId>
 <artifactId>scp-cf</artifactId>

Does this affect ? 

Regards,
Divya

**Comment by liga-oz** [comment]
> I am doing it using the below code : ` class CustomHybridTokenAuthenticationConverter implements Converter<Jwt, AbstractAuthenticationToken> {
> 
> ```
>     public AbstractAuthenticationToken convert(Jwt jwt) {
>         if (jwt.hasClaim(TokenClaims.XSUAA.SCOPES)) {
>             logger.info("jwt :"+ jwt.getTokenValue());
>             logger.info("jwt scopes:"+ jwt.getClaimAsString(TokenClaims.XSUAA.SCOPES));
>            // authConverter.convert(jwt);
>         }
>         return new AuthenticationToken(jwt, deriveAuthoritiesFromScope(jwt));
>     }
> 
>     private Collection<GrantedAuthority> deriveAuthoritiesFromScope(Jwt jwt) {
>         Collection<GrantedAuthority> scopeAuthorities = new ArrayList<>();
>         if (jwt.hasClaim(TokenClaims.XSUAA.SCOPES)) {
>             List<String> scopes = jwt.getClaimAsStringList(TokenClaims.XSUAA.SCOPES);
>             for (String scope : scopes) {
>                 logger.info("scope added:"+ scope);
>                 scopeAuthorities.add(new SimpleGrantedAuthority(scope));
>             }
>             logger.info("scopes :"+ scopeAuthorities.toString());
> 
>         }
>         return scopeAuthorities;
>     }
> }`
> ```
> 
> This did not fail till now.
> 
> But what are your views for this ? Any issue you see ?
> 
> Regards, Divya

Is application **authorization** working as expected?

> @liga-oz : Also what is the recommended version of library for

From our client-library perspective recommended version is always the latest.

> com.sap.cloud.sdk.cloudplatform
> scp-cf
> 
> Does this affect ?

To my knowledge no, as far as I know scp-cf uses our token-client module internally. Does your first application that successfully starts use the scp-cf dependency as well?

Kind Regards,
Liga

**Comment by divyathaore** [comment]
Hi @liga-oz ,

The first application that starts successfully, but the asynchronous calls are not happening. I have updated the scp-cf library version to the latest as well and then getting some more errors.

few errors which I encountered after updating the tenant accessor library are :
1) with version 3.75.0 :
>Application=acrscore-java, DCComponent=]:: Decorating callable for context: DefaultThreadContext(thread=Thread[http-nio-0.0.0.0-8080-exec-4,5,main], properties={com.sap.cloud.sdk.cloudplatform.security.AuthTokenThreadContextListener:authToken=Failure(com.sap.cloud.sdk.cloudplatform.security.exception.AuthTokenAccessException: Failed to verify JWT bearer.), com.sap.cloud.sdk.cloudplatform.tenant.TenantThreadContextListener:tenant=Success(Property(value=ScpCfTenant(super=DefaultTenant(tenantId=5ecd41ca-383a-4de0-8cac-0580088d99b0), subdomain=slhacrdev))), com.sap.cloud.sdk.cloudplatform.servlet.RequestThreadContextListener:request=Success(Property(value=com.sap.srfaas.util.fw.XssRequestWrapper@2a314925)), com.sap.cloud.sdk.cloudplatform.security.principal.PrincipalThreadContextListener:principal=Failure(com.sap.cloud.sdk.cloudplatform.security.exception.AuthTokenAccessException: Failed to verify JWT bearer.), com.sap.cloud.sdk.cloudplatform.connectivity.HttpClientsThreadContextListener:httpClients=Success(Property(value=com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalManualCache@72d75d1e))}).

2) with version 4.0.0
> c.s.c.s.c.s.RequestAccessorFilter [tenant_id=c6f1ea85-e493-4b4e-92b3-0b3e9a2a211a, correlation_id=54477868-8064-4df6-b89d-0da6c22a2945, CSNComponent=, Application=acrscore-java, DCComponent=]:: Unexpected servlet filter exception: com.auth0.jwt.interfaces.Claim.isMissing()Z
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT java.lang.NoSuchMethodError: com.auth0.jwt.interfaces.Claim.isMissing()Z
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at com.sap.cloud.sdk.cloudplatform.security.principal.OAuth2AuthTokenPrincipalExtractor.lambda$getPrincipalId$c8b7f4af$1(OAuth2AuthTokenPrincipalExtractor.java:87)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at io.vavr.control.Try.of(Try.java:75)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at com.sap.cloud.sdk.cloudplatform.security.principal.OAuth2AuthTokenPrincipalExtractor.getPrincipalId(OAuth2AuthTokenPrincipalExtractor.java:85)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at com.sap.cloud.sdk.cloudplatform.security.principal.OAuth2AuthTokenPrincipalExtractor.tryGetCurrentPrincipal(OAuth2AuthTokenPrincipalExtractor.java:244)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at com.sap.cloud.sdk.cloudplatform.security.principal.ScpCfPrincipalFacade.tryGetCurrentPrincipal(ScpCfPrincipalFacade.java:90)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at io.vavr.control.Try.flatMapTry(Try.java:490)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at io.vavr.control.Try.flatMap(Try.java:472)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at com.sap.cloud.sdk.cloudplatform.security.principal.PrincipalAccessor.tryGetCurrentPrincipal(PrincipalAccessor.java:110)
2022-10-17T12:55:20.036+0000 [APP/PROC/WEB/0] OUT at com.sap.cloud.sdk.cloudplatform.security.principal.PrincipalAccessor.getCurrentPrincipal(PrincipalAccessor.java:93)

Any clue ?

Regards,
Divya

**Comment by liga-oz** [comment]
Hi @divyathaore,

you need to ask these questions to cloud sdk colleagues, but with major release I would expect incompatible changes, so perhaps it's a good idea to look into version's 4.0.0 release notes.

Kind Regards,
Liga

**Comment by liga-oz** [comment]
closing due to inactivity
